### PR TITLE
Testing Github Actions

### PR DESCRIPTION
**Pull request by kojix2**

### CODE REVIEW

**Comment by kojix2** [comment]
Confirm that it works.

**Comment by kojix2** [comment]
Because this was just a trial.
Is it okay to have so many options?
If you are okay with that, I will send another pull request.

**Comment by hsbt** [comment]
No problem. We have no CI environment yet. The many options is better than nothing.

**Comment by kojix2** [comment]
Okay, I understand. I've resent the pull request.
Thank you for your cooperation.

**Pull request closed without merging**
