### PR TITLE
Fix Tk::Text#count not sending arguments to tcl.

### PR DESCRIPTION
**Pull request by iamvain**

### CODE REVIEW

**Comment by yuki24** [comment]
Thanks for your PR. Could you add a test that covers your change?

**Comment by amatsuda** [comment]
@yuki24 Great review basically... but how can one add a test for this repo? 🤔

**Comment by yuki24** [comment]
💥

**Comment by amatsuda** [comment]
Actually I’ll blindly merge this, because this fix seems to be obviously fixing a silly mistake.

**Pull request merged**
